# read.plink.tfam() runs LOCALLY on the master, but reads/writes from/to the HDFS
read.plink.tfam <- function(
  tfam.hdfs.path,    # space-delimited tped as generated by PLINK
  output.hdfs.path,  # must end in .RData
  is.cleanup=T,      # delete ./tmp/
  is.quiet=T         # don't return the matrix to the console
) {

  rhinit.singleton()

  # get from hdfs
  LOCAL = "./tmp"
  cat("[BlueSNP] copy from HDFS", tfam.hdfs.path, "to", LOCAL, "\n")
  if (!file.exists(LOCAL)) { dir.create(LOCAL, recursive=T) }
  rhget(tfam.hdfs.path, LOCAL)
  
  local.file = paste(LOCAL, "/", stripPath(tfam.hdfs.path), sep="")

  # assume tfam file fits in memory
  d = read.table(local.file)

  # relevant columns
  iid = as.character(d[,2])  # individual id
  Y = as.matrix(d[,-c(1:5)]) # phenotype matrix

  rownames(Y) = iid
  colnames(Y) = paste("trait", 1:(ncol(d)-5), sep="")

  outfile = stripPath(output.hdfs.path)
  cat("[BlueSNP] saving local file: ", outfile, "\n")
  save(file=outfile, list=c("Y"))

  cat("[BlueSNP] copy from", stripPath(outfile)," to HDFS", output.hdfs.path, "\n")
  rhput(outfile, output.hdfs.path)

  if (is.cleanup) {
    cat("[BlueSNP] removing", LOCAL, "\n")
    system(paste("rm -r", LOCAL))
  }

  if (!is.quiet)
    Y

}
